import type { FurnitureDefinition, FurnitureType } from "./FurnitureTypes";

export const FURNITURE_REGISTRY = {
  "chair-nebula": {
    id: "chair-nebula",
    name: "chair-nebula",
    label: "Chaise Nebula",
    sprite: "chair-nebula",
    storagePath: "sprites/furnitures/chair-nebula.png",
    width: 1,
    depth: 1,
    height: 1,
    offsetX: 0,
    offsetY: 6,
    walkable: false,
    drawWidth: 64,
    drawHeight: 64,
    glow: "rgba(0, 224, 255, 0.34)"
  },
  "table-prism": {
    id: "table-prism",
    name: "table-prism",
    label: "Table Prism",
    sprite: "table-prism",
    storagePath: "sprites/furnitures/table-prism.png",
    width: 2,
    depth: 2,
    height: 1,
    offsetX: 0,
    offsetY: 4,
    walkable: false,
    drawWidth: 96,
    drawHeight: 80
  },
  "bed-obsidian": {
    id: "bed-obsidian",
    name: "bed-obsidian",
    label: "Lit Obsidian",
    sprite: "bed-obsidian",
    storagePath: "sprites/furnitures/bed-obsidian.png",
    width: 2,
    depth: 3,
    height: 1,
    offsetX: 2,
    offsetY: 10,
    walkable: false,
    drawWidth: 112,
    drawHeight: 96
  },
  "lamp-halo": {
    id: "lamp-halo",
    name: "lamp-halo",
    label: "Lampe Halo",
    sprite: "lamp-halo",
    storagePath: "sprites/furnitures/lamp-halo.png",
    width: 1,
    depth: 1,
    height: 2,
    offsetX: 0,
    offsetY: -10,
    walkable: false,
    drawWidth: 64,
    drawHeight: 96,
    glow: "rgba(255, 232, 163, 0.34)"
  },
  "crystal-ether": {
    id: "crystal-ether",
    name: "crystal-ether",
    label: "Cristal Ether",
    sprite: "crystal-ether",
    storagePath: "sprites/furnitures/crystal-ether.png",
    width: 1,
    depth: 1,
    height: 2,
    offsetX: 0,
    offsetY: -4,
    walkable: false,
    drawWidth: 64,
    drawHeight: 84,
    glow: "rgba(0, 224, 255, 0.42)"
  },
  "neon-crown": {
    id: "neon-crown",
    name: "neon-crown",
    label: "Neon Crown",
    sprite: "neon-crown",
    storagePath: "sprites/furnitures/neon-crown.png",
    width: 1,
    depth: 1,
    height: 1,
    offsetX: 0,
    offsetY: -2,
    walkable: false,
    drawWidth: 64,
    drawHeight: 72,
    glow: "rgba(255, 87, 120, 0.28)"
  },

  "window-city-wide": {
    id: "window-city-wide",
    name: "window-city-wide",
    label: "Fenêtre Ville Large",
    sprite: "window-city-wide",
    storagePath: "sprites/furnitures/window-city-wide.png",
    width: 2,
    depth: 1,
    height: 3,
    offsetX: 0,
    offsetY: -44,
    walkable: false,
    drawWidth: 164,
    drawHeight: 132,
    glow: "rgba(139, 212, 255, 0.35)"
  },
  "window-city-wide-gold": {
    id: "window-city-wide-gold",
    name: "window-city-wide-gold",
    label: "Fenêtre Ville Gold",
    sprite: "window-city-wide-gold",
    storagePath: "sprites/furnitures/window-city-wide-gold.png",
    width: 2,
    depth: 1,
    height: 3,
    offsetX: 0,
    offsetY: -44,
    walkable: false,
    drawWidth: 170,
    drawHeight: 138,
    glow: "rgba(255, 210, 122, 0.35)"
  },
  "tv-wall-black": {
    id: "tv-wall-black",
    name: "tv-wall-black",
    label: "TV Murale Noire",
    sprite: "tv-wall-black",
    storagePath: "sprites/furnitures/tv-wall-black.png",
    width: 2,
    depth: 1,
    height: 2,
    offsetX: 0,
    offsetY: -16,
    walkable: false,
    drawWidth: 98,
    drawHeight: 84,
    glow: "rgba(127, 200, 255, 0.26)"
  },
  "media-console-black": {
    id: "media-console-black",
    name: "media-console-black",
    label: "Console Média Noire",
    sprite: "media-console-black",
    storagePath: "sprites/furnitures/media-console-black.png",
    width: 2,
    depth: 1,
    height: 1,
    offsetX: 0,
    offsetY: 8,
    walkable: false,
    drawWidth: 92,
    drawHeight: 48
  },
  "sectional-sofa-dark": {
    id: "sectional-sofa-dark",
    name: "sectional-sofa-dark",
    label: "Canapé Sectionnel Dark",
    sprite: "sectional-sofa-dark",
    storagePath: "sprites/furnitures/sectional-sofa-dark.png",
    width: 2,
    depth: 1,
    height: 1,
    offsetX: 0,
    offsetY: 10,
    walkable: false,
    drawWidth: 92,
    drawHeight: 62
  },
  "sectional-sofa-dark-corner": {
    id: "sectional-sofa-dark-corner",
    name: "sectional-sofa-dark-corner",
    label: "Coin Canapé Dark",
    sprite: "sectional-sofa-dark-corner",
    storagePath: "sprites/furnitures/sectional-sofa-dark-corner.png",
    width: 2,
    depth: 2,
    height: 1,
    offsetX: 0,
    offsetY: 12,
    walkable: false,
    drawWidth: 104,
    drawHeight: 74
  },
  "rug-gray-large": {
    id: "rug-gray-large",
    name: "rug-gray-large",
    label: "Tapis Gris Large",
    sprite: "rug-gray-large",
    storagePath: "sprites/furnitures/rug-gray-large.png",
    width: 3,
    depth: 2,
    height: 0,
    offsetX: 0,
    offsetY: 22,
    walkable: true,
    drawWidth: 148,
    drawHeight: 58
  },
  "coffee-table-glass": {
    id: "coffee-table-glass",
    name: "coffee-table-glass",
    label: "Table Basse Verre",
    sprite: "coffee-table-glass",
    storagePath: "sprites/furnitures/coffee-table-glass.png",
    width: 2,
    depth: 1,
    height: 1,
    offsetX: 0,
    offsetY: 14,
    walkable: false,
    drawWidth: 78,
    drawHeight: 48
  },
  "desk-l-modern": {
    id: "desk-l-modern",
    name: "desk-l-modern",
    label: "Bureau L Moderne",
    sprite: "desk-l-modern",
    storagePath: "sprites/furnitures/desk-l-modern.png",
    width: 3,
    depth: 2,
    height: 1,
    offsetX: 0,
    offsetY: 10,
    walkable: false,
    drawWidth: 138,
    drawHeight: 84
  },
  "monitor-flat-27": {
    id: "monitor-flat-27",
    name: "monitor-flat-27",
    label: "Écran 27 Plat",
    sprite: "monitor-flat-27",
    storagePath: "sprites/furnitures/monitor-flat-27.png",
    width: 1,
    depth: 1,
    height: 1,
    offsetX: 0,
    offsetY: -10,
    walkable: false,
    drawWidth: 42,
    drawHeight: 44,
    glow: "rgba(126, 216, 255, 0.28)"
  },
  "office-chair-black": {
    id: "office-chair-black",
    name: "office-chair-black",
    label: "Chaise Bureau Noire",
    sprite: "office-chair-black",
    storagePath: "sprites/furnitures/office-chair-black.png",
    width: 1,
    depth: 1,
    height: 1,
    offsetX: 0,
    offsetY: 10,
    walkable: false,
    drawWidth: 46,
    drawHeight: 58
  },
  "wall-shelf-minimal": {
    id: "wall-shelf-minimal",
    name: "wall-shelf-minimal",
    label: "Étagère Murale Minimal",
    sprite: "wall-shelf-minimal",
    storagePath: "sprites/furnitures/wall-shelf-minimal.png",
    width: 2,
    depth: 1,
    height: 2,
    offsetX: 0,
    offsetY: -18,
    walkable: false,
    drawWidth: 88,
    drawHeight: 58
  },
  "floor-lamp-white": {
    id: "floor-lamp-white",
    name: "floor-lamp-white",
    label: "Lampe Sol Blanche",
    sprite: "floor-lamp-white",
    storagePath: "sprites/furnitures/floor-lamp-white.png",
    width: 1,
    depth: 1,
    height: 2,
    offsetX: 0,
    offsetY: -12,
    walkable: false,
    drawWidth: 42,
    drawHeight: 76,
    glow: "rgba(255, 230, 184, 0.32)"
  },
  "plant-tall-modern": {
    id: "plant-tall-modern",
    name: "plant-tall-modern",
    label: "Grande Plante Moderne",
    sprite: "plant-tall-modern",
    storagePath: "sprites/furnitures/plant-tall-modern.png",
    width: 1,
    depth: 1,
    height: 2,
    offsetX: 0,
    offsetY: -8,
    walkable: false,
    drawWidth: 52,
    drawHeight: 74
  },
  "fridge-steel": {
    id: "fridge-steel",
    name: "fridge-steel",
    label: "Frigo Acier",
    sprite: "fridge-steel",
    storagePath: "sprites/furnitures/fridge-steel.png",
    width: 1,
    depth: 1,
    height: 2,
    offsetX: 0,
    offsetY: -16,
    walkable: false,
    drawWidth: 54,
    drawHeight: 88
  },
  "cabinet-dark-low": {
    id: "cabinet-dark-low",
    name: "cabinet-dark-low",
    label: "Cabinet Bas Dark",
    sprite: "cabinet-dark-low",
    storagePath: "sprites/furnitures/cabinet-dark-low.png",
    width: 2,
    depth: 1,
    height: 1,
    offsetX: 0,
    offsetY: 10,
    walkable: false,
    drawWidth: 90,
    drawHeight: 54
  },
  "kitchen-line-dark": {
    id: "kitchen-line-dark",
    name: "kitchen-line-dark",
    label: "Cuisine Linéaire Dark",
    sprite: "kitchen-line-dark",
    storagePath: "sprites/furnitures/kitchen-line-dark.png",
    width: 3,
    depth: 1,
    height: 2,
    offsetX: 0,
    offsetY: -6,
    walkable: false,
    drawWidth: 138,
    drawHeight: 86
  },

  "chandelier-grand-gold": {
    id: "chandelier-grand-gold",
    name: "chandelier-grand-gold",
    label: "Grand Lustre Gold",
    sprite: "chandelier-grand-gold",
    storagePath: "sprites/furnitures/chandelier-grand-gold.png",
    width: 2,
    depth: 2,
    height: 3,
    offsetX: 0,
    offsetY: -68,
    walkable: false,
    drawWidth: 110,
    drawHeight: 140,
    glow: "rgba(255, 217, 120, 0.38)"
  },
  "bed-royal-red": {
    id: "bed-royal-red",
    name: "bed-royal-red",
    label: "Lit Royal Rouge",
    sprite: "bed-royal-red",
    storagePath: "sprites/furnitures/bed-royal-red.png",
    width: 3,
    depth: 2,
    height: 1,
    offsetX: 0,
    offsetY: 8,
    walkable: false,
    drawWidth: 154,
    drawHeight: 102,
    glow: "rgba(255, 191, 114, 0.24)"
  },
  "nightstand-gold": {
    id: "nightstand-gold",
    name: "nightstand-gold",
    label: "Table de Nuit Gold",
    sprite: "nightstand-gold",
    storagePath: "sprites/furnitures/nightstand-gold.png",
    width: 1,
    depth: 1,
    height: 1,
    offsetX: 0,
    offsetY: 10,
    walkable: false,
    drawWidth: 44,
    drawHeight: 52
  },
  "grand-piano-black": {
    id: "grand-piano-black",
    name: "grand-piano-black",
    label: "Piano à Queue Noir",
    sprite: "grand-piano-black",
    storagePath: "sprites/furnitures/grand-piano-black.png",
    width: 2,
    depth: 3,
    height: 1,
    offsetX: 0,
    offsetY: 4,
    walkable: false,
    drawWidth: 126,
    drawHeight: 98
  },
  "fireplace-classic": {
    id: "fireplace-classic",
    name: "fireplace-classic",
    label: "Cheminée Classique",
    sprite: "fireplace-classic",
    storagePath: "sprites/furnitures/fireplace-classic.png",
    width: 2,
    depth: 1,
    height: 2,
    offsetX: 0,
    offsetY: -8,
    walkable: false,
    drawWidth: 82,
    drawHeight: 88,
    glow: "rgba(255, 178, 90, 0.35)"
  },
  "sofa-ivory": {
    id: "sofa-ivory",
    name: "sofa-ivory",
    label: "Canapé Ivoire",
    sprite: "sofa-ivory",
    storagePath: "sprites/furnitures/sofa-ivory.png",
    width: 2,
    depth: 1,
    height: 1,
    offsetX: 0,
    offsetY: 10,
    walkable: false,
    drawWidth: 88,
    drawHeight: 60
  },
  "lounge-chair-ivory": {
    id: "lounge-chair-ivory",
    name: "lounge-chair-ivory",
    label: "Fauteuil Ivoire",
    sprite: "lounge-chair-ivory",
    storagePath: "sprites/furnitures/lounge-chair-ivory.png",
    width: 1,
    depth: 1,
    height: 1,
    offsetX: 0,
    offsetY: 10,
    walkable: false,
    drawWidth: 54,
    drawHeight: 62
  },
  "coffee-table-gold": {
    id: "coffee-table-gold",
    name: "coffee-table-gold",
    label: "Table Basse Gold",
    sprite: "coffee-table-gold",
    storagePath: "sprites/furnitures/coffee-table-gold.png",
    width: 2,
    depth: 1,
    height: 1,
    offsetX: 0,
    offsetY: 12,
    walkable: false,
    drawWidth: 82,
    drawHeight: 50
  },
  "bar-marble-black": {
    id: "bar-marble-black",
    name: "bar-marble-black",
    label: "Bar Marbre Noir",
    sprite: "bar-marble-black",
    storagePath: "sprites/furnitures/bar-marble-black.png",
    width: 3,
    depth: 1,
    height: 1,
    offsetX: 0,
    offsetY: 8,
    walkable: false,
    drawWidth: 132,
    drawHeight: 74
  },
  "bar-stool-gold": {
    id: "bar-stool-gold",
    name: "bar-stool-gold",
    label: "Tabouret Gold",
    sprite: "bar-stool-gold",
    storagePath: "sprites/furnitures/bar-stool-gold.png",
    width: 1,
    depth: 1,
    height: 1,
    offsetX: 0,
    offsetY: 12,
    walkable: false,
    drawWidth: 42,
    drawHeight: 50
  },
  "jacuzzi-round-gold": {
    id: "jacuzzi-round-gold",
    name: "jacuzzi-round-gold",
    label: "Jacuzzi Rond Gold",
    sprite: "jacuzzi-round-gold",
    storagePath: "sprites/furnitures/jacuzzi-round-gold.png",
    width: 2,
    depth: 2,
    height: 1,
    offsetX: 0,
    offsetY: 12,
    walkable: false,
    drawWidth: 110,
    drawHeight: 76,
    glow: "rgba(136, 222, 255, 0.34)"
  },
  "statue-gold": {
    id: "statue-gold",
    name: "statue-gold",
    label: "Statue Gold",
    sprite: "statue-gold",
    storagePath: "sprites/furnitures/statue-gold.png",
    width: 1,
    depth: 1,
    height: 2,
    offsetX: 0,
    offsetY: -12,
    walkable: false,
    drawWidth: 46,
    drawHeight: 88,
    glow: "rgba(255, 216, 127, 0.30)"
  },
  "rug-royal-red": {
    id: "rug-royal-red",
    name: "rug-royal-red",
    label: "Tapis Royal Rouge",
    sprite: "rug-royal-red",
    storagePath: "sprites/furnitures/rug-royal-red.png",
    width: 3,
    depth: 2,
    height: 0,
    offsetX: 0,
    offsetY: 22,
    walkable: true,
    drawWidth: 150,
    drawHeight: 60
  },
  "shelf-luxury-backbar": {
    id: "shelf-luxury-backbar",
    name: "shelf-luxury-backbar",
    label: "Étagère Backbar Luxe",
    sprite: "shelf-luxury-backbar",
    storagePath: "sprites/furnitures/shelf-luxury-backbar.png",
    width: 3,
    depth: 1,
    height: 2,
    offsetX: 0,
    offsetY: -10,
    walkable: false,
    drawWidth: 136,
    drawHeight: 92
  },

  "waterfall-wall": {
    id: "waterfall-wall",
    name: "waterfall-wall",
    label: "Mur Cascade",
    sprite: "waterfall-wall",
    storagePath: "sprites/furnitures/waterfall-wall.png",
    width: 2,
    depth: 1,
    height: 3,
    offsetX: 0,
    offsetY: -30,
    walkable: false,
    drawWidth: 116,
    drawHeight: 130,
    glow: "rgba(140, 233, 255, 0.35)"
  },
  "bed-tiki-canopy": {
    id: "bed-tiki-canopy",
    name: "bed-tiki-canopy",
    label: "Lit Tiki Canopée",
    sprite: "bed-tiki-canopy",
    storagePath: "sprites/furnitures/bed-tiki-canopy.png",
    width: 3,
    depth: 2,
    height: 2,
    offsetX: 0,
    offsetY: 2,
    walkable: false,
    drawWidth: 154,
    drawHeight: 108
  },
  "bar-tiki-bamboo": {
    id: "bar-tiki-bamboo",
    name: "bar-tiki-bamboo",
    label: "Bar Tiki Bambou",
    sprite: "bar-tiki-bamboo",
    storagePath: "sprites/furnitures/bar-tiki-bamboo.png",
    width: 3,
    depth: 1,
    height: 2,
    offsetX: 0,
    offsetY: -2,
    walkable: false,
    drawWidth: 136,
    drawHeight: 94
  },
  "stool-tiki": {
    id: "stool-tiki",
    name: "stool-tiki",
    label: "Tabouret Tiki",
    sprite: "stool-tiki",
    storagePath: "sprites/furnitures/stool-tiki.png",
    width: 1,
    depth: 1,
    height: 1,
    offsetX: 0,
    offsetY: 12,
    walkable: false,
    drawWidth: 38,
    drawHeight: 44
  },
  "pool-plunge-stone": {
    id: "pool-plunge-stone",
    name: "pool-plunge-stone",
    label: "Piscine Pierre",
    sprite: "pool-plunge-stone",
    storagePath: "sprites/furnitures/pool-plunge-stone.png",
    width: 3,
    depth: 2,
    height: 0,
    offsetX: 0,
    offsetY: 18,
    walkable: false,
    drawWidth: 146,
    drawHeight: 78,
    glow: "rgba(132, 229, 255, 0.32)"
  },
  "firepit-stone": {
    id: "firepit-stone",
    name: "firepit-stone",
    label: "Feu de Camp Pierre",
    sprite: "firepit-stone",
    storagePath: "sprites/furnitures/firepit-stone.png",
    width: 2,
    depth: 2,
    height: 1,
    offsetX: 0,
    offsetY: 14,
    walkable: false,
    drawWidth: 84,
    drawHeight: 64,
    glow: "rgba(255, 184, 95, 0.35)"
  },
  "chair-wicker": {
    id: "chair-wicker",
    name: "chair-wicker",
    label: "Chaise Osier",
    sprite: "chair-wicker",
    storagePath: "sprites/furnitures/chair-wicker.png",
    width: 1,
    depth: 1,
    height: 1,
    offsetX: 0,
    offsetY: 10,
    walkable: false,
    drawWidth: 46,
    drawHeight: 54
  },
  "table-tiki-low": {
    id: "table-tiki-low",
    name: "table-tiki-low",
    label: "Table Tiki Basse",
    sprite: "table-tiki-low",
    storagePath: "sprites/furnitures/table-tiki-low.png",
    width: 2,
    depth: 1,
    height: 1,
    offsetX: 0,
    offsetY: 14,
    walkable: false,
    drawWidth: 74,
    drawHeight: 42
  },
  "hammock-cream": {
    id: "hammock-cream",
    name: "hammock-cream",
    label: "Hamac Crème",
    sprite: "hammock-cream",
    storagePath: "sprites/furnitures/hammock-cream.png",
    width: 2,
    depth: 1,
    height: 2,
    offsetX: 0,
    offsetY: -8,
    walkable: false,
    drawWidth: 104,
    drawHeight: 64
  },
  "surfboard-yellow": {
    id: "surfboard-yellow",
    name: "surfboard-yellow",
    label: "Surf Jaune",
    sprite: "surfboard-yellow",
    storagePath: "sprites/furnitures/surfboard-yellow.png",
    width: 1,
    depth: 1,
    height: 2,
    offsetX: 0,
    offsetY: -18,
    walkable: false,
    drawWidth: 32,
    drawHeight: 82
  },
  "palm-tree-tall": {
    id: "palm-tree-tall",
    name: "palm-tree-tall",
    label: "Palmier Haut",
    sprite: "palm-tree-tall",
    storagePath: "sprites/furnitures/palm-tree-tall.png",
    width: 1,
    depth: 1,
    height: 3,
    offsetX: 0,
    offsetY: -54,
    walkable: false,
    drawWidth: 74,
    drawHeight: 124
  },
  "torch-tiki": {
    id: "torch-tiki",
    name: "torch-tiki",
    label: "Torche Tiki",
    sprite: "torch-tiki",
    storagePath: "sprites/furnitures/torch-tiki.png",
    width: 1,
    depth: 1,
    height: 2,
    offsetX: 0,
    offsetY: -10,
    walkable: false,
    drawWidth: 30,
    drawHeight: 74,
    glow: "rgba(255, 191, 108, 0.36)"
  },
  "sofa-tiki-lounge": {
    id: "sofa-tiki-lounge",
    name: "sofa-tiki-lounge",
    label: "Lounge Tiki",
    sprite: "sofa-tiki-lounge",
    storagePath: "sprites/furnitures/sofa-tiki-lounge.png",
    width: 2,
    depth: 1,
    height: 1,
    offsetX: 0,
    offsetY: 10,
    walkable: false,
    drawWidth: 92,
    drawHeight: 58
  },
  "rug-sand-warm": {
    id: "rug-sand-warm",
    name: "rug-sand-warm",
    label: "Tapis Sable",
    sprite: "rug-sand-warm",
    storagePath: "sprites/furnitures/rug-sand-warm.png",
    width: 2,
    depth: 2,
    height: 0,
    offsetX: 0,
    offsetY: 22,
    walkable: true,
    drawWidth: 110,
    drawHeight: 52
  },
  "shelf-tiki-drinks": {
    id: "shelf-tiki-drinks",
    name: "shelf-tiki-drinks",
    label: "Étagère Tiki Drinks",
    sprite: "shelf-tiki-drinks",
    storagePath: "sprites/furnitures/shelf-tiki-drinks.png",
    width: 2,
    depth: 1,
    height: 2,
    offsetX: 0,
    offsetY: -8,
    walkable: false,
    drawWidth: 96,
    drawHeight: 84
  }
} as Record<string, FurnitureDefinition>;

export const FURNITURE_ORDER = Object.keys(FURNITURE_REGISTRY) as FurnitureType[];

export function getFurnitureDefinition(type: FurnitureType | string) {
  return FURNITURE_REGISTRY[type as string];
}

export function getFurnitureSpritePath(type: FurnitureType | string) {
  return `/sprites/furnitures/${FURNITURE_REGISTRY[type as string].sprite}.png`;
}
