import type { FurnitureDefinition, FurnitureType } from "./FurnitureTypes";

const MEUBLES = "/sprites/furnitures/meubles";
const SHOP = "/sprites/furnitures/shop";
const CANNABIS = "/sprites/furnitures/cannabis";

export const FURNITURE_REGISTRY: Record<FurnitureType, FurnitureDefinition> = {
  "chair-nebula": {
    id: "chair-nebula",
    name: "chair-nebula",
    label: "Chaise Nebula",
    sprite: "chair-nebula",
    spriteUrl: `${MEUBLES}/chair-nebula.png`,
    storagePath: "sprites/furnitures/meubles/chair-nebula.png",
    width: 1,
    depth: 1,
    height: 1,
    offsetX: 0,
    offsetY: 6,
    walkable: false,
    drawWidth: 64,
    drawHeight: 64,
    glow: "rgba(0, 224, 255, 0.34)"
  },
  "table-prism": {
    id: "table-prism",
    name: "table-prism",
    label: "Table Prism",
    sprite: "table-prism",
    spriteUrl: `${MEUBLES}/table-prism.png`,
    storagePath: "sprites/furnitures/meubles/table-prism.png",
    width: 2,
    depth: 2,
    height: 1,
    offsetX: 0,
    offsetY: 4,
    walkable: false,
    drawWidth: 96,
    drawHeight: 80
  },
  "bed-obsidian": {
    id: "bed-obsidian",
    name: "bed-obsidian",
    label: "Lit Obsidian",
    sprite: "bed-obsidian",
    spriteUrl: `${MEUBLES}/bed-obsidian.png`,
    storagePath: "sprites/furnitures/meubles/bed-obsidian.png",
    width: 2,
    depth: 3,
    height: 1,
    offsetX: 2,
    offsetY: 10,
    walkable: false,
    drawWidth: 112,
    drawHeight: 96
  },
  "lamp-halo": {
    id: "lamp-halo",
    name: "lamp-halo",
    label: "Lampe Halo",
    sprite: "lamp-halo",
    spriteUrl: `${MEUBLES}/lamp-halo.png`,
    storagePath: "sprites/furnitures/meubles/lamp-halo.png",
    width: 1,
    depth: 1,
    height: 2,
    offsetX: 0,
    offsetY: -10,
    walkable: false,
    drawWidth: 64,
    drawHeight: 96,
    glow: "rgba(255, 232, 163, 0.34)"
  },
  "crystal-ether": {
    id: "crystal-ether",
    name: "crystal-ether",
    label: "Cristal Ether",
    sprite: "crystal-ether",
    spriteUrl: `${MEUBLES}/crystal-ether.png`,
    storagePath: "sprites/furnitures/meubles/crystal-ether.png",
    width: 1,
    depth: 1,
    height: 2,
    offsetX: 0,
    offsetY: -4,
    walkable: false,
    drawWidth: 64,
    drawHeight: 84,
    glow: "rgba(0, 224, 255, 0.42)"
  },
  "neon-crown": {
    id: "neon-crown",
    name: "neon-crown",
    label: "Neon Crown",
    sprite: "neon-crown",
    spriteUrl: `${MEUBLES}/neon-crown.png`,
    storagePath: "sprites/furnitures/meubles/neon-crown.png",
    width: 1,
    depth: 1,
    height: 1,
    offsetX: 0,
    offsetY: -2,
    walkable: false,
    drawWidth: 64,
    drawHeight: 72,
    glow: "rgba(255, 87, 120, 0.28)"
  },

  // ===== Weed Shop =====
  "shop-counter": {
    id: "shop-counter",
    name: "shop-counter",
    label: "Comptoir Vendeur",
    sprite: "shop-counter",
    spriteUrl: `${SHOP}/shop-counter.svg`,
    storagePath: "sprites/furnitures/shop/shop-counter.svg",
    width: 3,
    depth: 1,
    height: 1,
    offsetX: 0,
    offsetY: 10,
    walkable: false,
    drawWidth: 200,
    drawHeight: 120,
    glow: "rgba(95, 225, 142, 0.35)"
  },
  "shop-counter-corner": {
    id: "shop-counter-corner",
    name: "shop-counter-corner",
    label: "Comptoir Angle",
    sprite: "shop-counter-corner",
    spriteUrl: `${SHOP}/shop-counter-corner.svg`,
    storagePath: "sprites/furnitures/shop/shop-counter-corner.svg",
    width: 1,
    depth: 1,
    height: 1,
    offsetX: 0,
    offsetY: 8,
    walkable: false,
    drawWidth: 100,
    drawHeight: 110,
    glow: "rgba(95, 225, 142, 0.35)"
  },
  "wall-shelf-jars": {
    id: "wall-shelf-jars",
    name: "wall-shelf-jars",
    label: "Etagere Jars",
    sprite: "wall-shelf-jars",
    spriteUrl: `${SHOP}/wall-shelf-jars.svg`,
    storagePath: "sprites/furnitures/shop/wall-shelf-jars.svg",
    width: 2,
    depth: 1,
    height: 2,
    offsetX: 0,
    offsetY: -18,
    walkable: false,
    drawWidth: 156,
    drawHeight: 140,
    glow: "rgba(95, 225, 142, 0.28)"
  },
  "wall-shelf-glass": {
    id: "wall-shelf-glass",
    name: "wall-shelf-glass",
    label: "Etagere Verrerie",
    sprite: "wall-shelf-glass",
    spriteUrl: `${SHOP}/wall-shelf-glass.svg`,
    storagePath: "sprites/furnitures/shop/wall-shelf-glass.svg",
    width: 2,
    depth: 1,
    height: 2,
    offsetX: 0,
    offsetY: -18,
    walkable: false,
    drawWidth: 156,
    drawHeight: 140,
    glow: "rgba(167, 234, 255, 0.28)"
  },
  "display-vitrine": {
    id: "display-vitrine",
    name: "display-vitrine",
    label: "Vitrine Premium",
    sprite: "display-vitrine",
    spriteUrl: `${SHOP}/display-vitrine.svg`,
    storagePath: "sprites/furnitures/shop/display-vitrine.svg",
    width: 1,
    depth: 1,
    height: 2,
    offsetX: 0,
    offsetY: -4,
    walkable: false,
    drawWidth: 72,
    drawHeight: 110,
    glow: "rgba(111, 233, 255, 0.38)"
  },
  "premium-display": {
    id: "premium-display",
    name: "premium-display",
    label: "Display Diamond",
    sprite: "premium-display",
    spriteUrl: `${SHOP}/premium-display.svg`,
    storagePath: "sprites/furnitures/shop/premium-display.svg",
    width: 2,
    depth: 1,
    height: 1,
    offsetX: 0,
    offsetY: 2,
    walkable: false,
    drawWidth: 150,
    drawHeight: 94,
    glow: "rgba(255, 214, 120, 0.36)"
  },
  "cash-register": {
    id: "cash-register",
    name: "cash-register",
    label: "Caisse Neon",
    sprite: "cash-register",
    spriteUrl: `${SHOP}/cash-register.svg`,
    storagePath: "sprites/furnitures/shop/cash-register.svg",
    width: 1,
    depth: 1,
    height: 1,
    offsetX: 0,
    offsetY: 0,
    walkable: false,
    drawWidth: 72,
    drawHeight: 78,
    glow: "rgba(95, 225, 142, 0.4)"
  },
  "weed-plant-tall": {
    id: "weed-plant-tall",
    name: "weed-plant-tall",
    label: "Plante Cannabis XL",
    sprite: "weed-plant-tall",
    spriteUrl: `${SHOP}/weed-plant-tall.svg`,
    storagePath: "sprites/furnitures/shop/weed-plant-tall.svg",
    width: 1,
    depth: 1,
    height: 2,
    offsetX: 0,
    offsetY: -10,
    walkable: false,
    drawWidth: 84,
    drawHeight: 140,
    glow: "rgba(125, 255, 150, 0.26)"
  },
  "weed-plant-bush": {
    id: "weed-plant-bush",
    name: "weed-plant-bush",
    label: "Plante Cannabis",
    sprite: "weed-plant-bush",
    spriteUrl: `${SHOP}/weed-plant-bush.svg`,
    storagePath: "sprites/furnitures/shop/weed-plant-bush.svg",
    width: 1,
    depth: 1,
    height: 1,
    offsetX: 0,
    offsetY: 4,
    walkable: false,
    drawWidth: 72,
    drawHeight: 78,
    glow: "rgba(125, 255, 150, 0.2)"
  },
  "neon-sign-green": {
    id: "neon-sign-green",
    name: "neon-sign-green",
    label: "Enseigne GREEN SHOP",
    sprite: "neon-sign-green",
    spriteUrl: `${SHOP}/neon-sign-green.svg`,
    storagePath: "sprites/furnitures/shop/neon-sign-green.svg",
    width: 3,
    depth: 1,
    height: 2,
    offsetX: 0,
    offsetY: -24,
    walkable: false,
    drawWidth: 220,
    drawHeight: 110,
    glow: "rgba(95, 255, 142, 0.6)"
  },
  "neon-leaf": {
    id: "neon-leaf",
    name: "neon-leaf",
    label: "Neon Feuille",
    sprite: "neon-leaf",
    spriteUrl: `${SHOP}/neon-leaf.svg`,
    storagePath: "sprites/furnitures/shop/neon-leaf.svg",
    width: 1,
    depth: 1,
    height: 2,
    offsetX: 0,
    offsetY: -12,
    walkable: false,
    drawWidth: 64,
    drawHeight: 86,
    glow: "rgba(95, 255, 142, 0.55)"
  },
  "dab-station": {
    id: "dab-station",
    name: "dab-station",
    label: "Station Dab",
    sprite: "dab-station",
    spriteUrl: `${SHOP}/dab-station.svg`,
    storagePath: "sprites/furnitures/shop/dab-station.svg",
    width: 1,
    depth: 1,
    height: 1,
    offsetX: 0,
    offsetY: 2,
    walkable: false,
    drawWidth: 72,
    drawHeight: 84,
    glow: "rgba(255, 210, 120, 0.34)"
  },
  "stash-cabinet": {
    id: "stash-cabinet",
    name: "stash-cabinet",
    label: "Armoire Stash",
    sprite: "stash-cabinet",
    spriteUrl: `${SHOP}/stash-cabinet.svg`,
    storagePath: "sprites/furnitures/shop/stash-cabinet.svg",
    width: 2,
    depth: 1,
    height: 2,
    offsetX: 0,
    offsetY: -12,
    walkable: false,
    drawWidth: 140,
    drawHeight: 132,
    glow: "rgba(95, 225, 142, 0.22)"
  },
  "chill-sofa": {
    id: "chill-sofa",
    name: "chill-sofa",
    label: "Canape Chill",
    sprite: "chill-sofa",
    spriteUrl: `${SHOP}/chill-sofa.svg`,
    storagePath: "sprites/furnitures/shop/chill-sofa.svg",
    width: 2,
    depth: 1,
    height: 1,
    offsetX: 0,
    offsetY: 8,
    walkable: false,
    drawWidth: 140,
    drawHeight: 86
  },
  "shop-rug": {
    id: "shop-rug",
    name: "shop-rug",
    label: "Tapis Shop",
    sprite: "shop-rug",
    spriteUrl: `${SHOP}/shop-rug.svg`,
    storagePath: "sprites/furnitures/shop/shop-rug.svg",
    width: 2,
    depth: 2,
    height: 1,
    offsetX: 0,
    offsetY: 14,
    walkable: true,
    drawWidth: 140,
    drawHeight: 70
  },
  "entry-mat": {
    id: "entry-mat",
    name: "entry-mat",
    label: "Paillasson Entree",
    sprite: "entry-mat",
    spriteUrl: `${SHOP}/entry-mat.svg`,
    storagePath: "sprites/furnitures/shop/entry-mat.svg",
    width: 2,
    depth: 1,
    height: 1,
    offsetX: 0,
    offsetY: 12,
    walkable: true,
    drawWidth: 128,
    drawHeight: 48
  },
  "poster-strain": {
    id: "poster-strain",
    name: "poster-strain",
    label: "Poster Strain",
    sprite: "poster-strain",
    spriteUrl: `${SHOP}/poster-strain.svg`,
    storagePath: "sprites/furnitures/shop/poster-strain.svg",
    width: 1,
    depth: 1,
    height: 2,
    offsetX: 0,
    offsetY: -18,
    walkable: false,
    drawWidth: 72,
    drawHeight: 96,
    glow: "rgba(255, 214, 120, 0.22)"
  },
  "rolling-tray": {
    id: "rolling-tray",
    name: "rolling-tray",
    label: "Rolling Tray",
    sprite: "rolling-tray",
    spriteUrl: `${CANNABIS}/rolling-tray.svg`,
    storagePath: "sprites/furnitures/cannabis/rolling-tray.svg",
    width: 1,
    depth: 1,
    height: 1,
    offsetX: 0,
    offsetY: 4,
    walkable: false,
    drawWidth: 72,
    drawHeight: 56
  },
  "menu-board": {
    id: "menu-board",
    name: "menu-board",
    label: "Menu Herbes",
    sprite: "menu-board",
    spriteUrl: `${SHOP}/menu-board.svg`,
    storagePath: "sprites/furnitures/shop/menu-board.svg",
    width: 1,
    depth: 1,
    height: 2,
    offsetX: 0,
    offsetY: -14,
    walkable: false,
    drawWidth: 72,
    drawHeight: 104,
    glow: "rgba(95, 255, 142, 0.3)"
  },
  "cannabis-jar-diamond": {
    id: "cannabis-jar-diamond",
    name: "cannabis-jar-diamond",
    label: "Jar Diamond Sauce",
    sprite: "cannabis-jar-diamond",
    spriteUrl: `${CANNABIS}/diamond-sauce-cereal-milk.svg`,
    storagePath: "sprites/furnitures/cannabis/diamond-sauce-cereal-milk.svg",
    width: 1,
    depth: 1,
    height: 1,
    offsetX: 0,
    offsetY: 6,
    walkable: false,
    drawWidth: 54,
    drawHeight: 62,
    glow: "rgba(255, 210, 120, 0.4)"
  },
  "cannabis-jar-live-resin": {
    id: "cannabis-jar-live-resin",
    name: "cannabis-jar-live-resin",
    label: "Jar Live Resin",
    sprite: "cannabis-jar-live-resin",
    spriteUrl: `${CANNABIS}/live-resin-sour-diesel.svg`,
    storagePath: "sprites/furnitures/cannabis/live-resin-sour-diesel.svg",
    width: 1,
    depth: 1,
    height: 1,
    offsetX: 0,
    offsetY: 6,
    walkable: false,
    drawWidth: 54,
    drawHeight: 62,
    glow: "rgba(255, 210, 120, 0.4)"
  },
  "cannabis-jar-hash": {
    id: "cannabis-jar-hash",
    name: "cannabis-jar-hash",
    label: "Hash Pressed",
    sprite: "cannabis-jar-hash",
    spriteUrl: `${CANNABIS}/hash-rosin-wedding-cake.svg`,
    storagePath: "sprites/furnitures/cannabis/hash-rosin-wedding-cake.svg",
    width: 1,
    depth: 1,
    height: 1,
    offsetX: 0,
    offsetY: 6,
    walkable: false,
    drawWidth: 54,
    drawHeight: 62
  },
  "cannabis-jar-pot": {
    id: "cannabis-jar-pot",
    name: "cannabis-jar-pot",
    label: "Jar Pot Premium",
    sprite: "cannabis-jar-pot",
    spriteUrl: `${CANNABIS}/glass-jar.svg`,
    storagePath: "sprites/furnitures/cannabis/glass-jar.svg",
    width: 1,
    depth: 1,
    height: 1,
    offsetX: 0,
    offsetY: 6,
    walkable: false,
    drawWidth: 54,
    drawHeight: 62,
    glow: "rgba(125, 255, 150, 0.3)"
  }
};

export const FURNITURE_ORDER = Object.keys(FURNITURE_REGISTRY) as FurnitureType[];

export const WEED_SHOP_FURNITURE: FurnitureType[] = [
  "shop-counter",
  "shop-counter-corner",
  "wall-shelf-jars",
  "wall-shelf-glass",
  "display-vitrine",
  "premium-display",
  "cash-register",
  "weed-plant-tall",
  "weed-plant-bush",
  "neon-sign-green",
  "neon-leaf",
  "dab-station",
  "stash-cabinet",
  "chill-sofa",
  "shop-rug",
  "entry-mat",
  "poster-strain",
  "rolling-tray",
  "menu-board",
  "cannabis-jar-diamond",
  "cannabis-jar-live-resin",
  "cannabis-jar-hash",
  "cannabis-jar-pot"
];

export function getFurnitureDefinition(type: FurnitureType) {
  return FURNITURE_REGISTRY[type];
}

export function getFurnitureSpritePath(type: FurnitureType) {
  const definition = FURNITURE_REGISTRY[type];
  return definition.spriteUrl ?? `/sprites/furnitures/${definition.sprite}.png`;
}
