import type { RoomDefinition } from "./types"

export const ETHERWORLD_ROOM: RoomDefinition = {
  title: "EtherWorld Suite",
  subtitle: "Room locale isométrique style hôtel",
  width: 10,
  height: 8,
  tileWidth: 64,
  tileHeight: 32,
  wallHeight: 124,
  floorDrop: 18,
  stepHeight: 26,
  moveSpeed: 3.3,
  startTile: { x: 2, y: 6 },
  furnitures: [
    {
      id: "sofa-main",
      label: "Sofa",
      kind: "sofa",
      x: 2,
      y: 2,
      w: 2,
      d: 1,
      h: 1,
      color: "#7d5579",
      accent: "#b989b2",
    },
    {
      id: "coffee-table",
      label: "Table",
      kind: "table",
      x: 4,
      y: 2,
      w: 1,
      d: 1,
      h: 1,
      color: "#a37c56",
      accent: "#d3a16e",
    },
    {
      id: "bed-royal",
      label: "Bed",
      kind: "bed",
      x: 6,
      y: 1,
      w: 2,
      d: 3,
      h: 1,
      color: "#8e374d",
      accent: "#d16485",
    },
    {
      id: "desk",
      label: "Desk",
      kind: "desk",
      x: 1,
      y: 5,
      w: 2,
      d: 1,
      h: 1,
      color: "#67503c",
      accent: "#9d7a57",
    },
    {
      id: "screen",
      label: "Screen",
      kind: "screen",
      x: 2,
      y: 5,
      w: 1,
      d: 1,
      h: 2,
      color: "#1d2430",
      accent: "#5fe4ff",
    },
    {
      id: "lamp",
      label: "Lamp",
      kind: "lamp",
      x: 8,
      y: 1,
      w: 1,
      d: 1,
      h: 2,
      color: "#d4c89c",
      accent: "#fff2a7",
    },
    {
      id: "plant",
      label: "Plant",
      kind: "plant",
      x: 8,
      y: 5,
      w: 1,
      d: 1,
      h: 2,
      color: "#355c42",
      accent: "#68b97e",
    },
    {
      id: "rug",
      label: "Rug",
      kind: "rug",
      x: 3,
      y: 4,
      w: 3,
      d: 2,
      h: 0,
      walkable: true,
      color: "#d5c29b",
      accent: "#efe1bf",
    },
  ],
}
